### PR TITLE
Added docker support

### PR DESCRIPTION
**Pull request by lingyuanzhicheng**
new file: Dockerfile
new file: docker-compose.yml
change file:readme.md

### CODE REVIEW

**Comment by lingyuanzhicheng** [comment]
我非常抱歉在 https://github.com/fatwang2/dify2openai/pull/3 中的错误。当时有事情在nas上测试后没注意到问题，直接copy了。

**Comment by lingyuanzhicheng** [comment]
根据 OpenAI  RESTful API ，增加了 `/v1/models` 端点。且可以提供环境变量自定义model_name

**Comment by potofo** [comment]
@fatwang2 
Could you please merge this pull request into the main branch?
Because the current main branch doesn't work.

**Comment by potofo** [comment]
@fatwang2 
Thank you for swift support.

**Pull request merged**
